src/Moonglade.Web/ViewComponents/MenuViewComponent.cs
namespace Moonglade.Web.ViewComponents;

public class MenuViewComponent(IBlogConfig blogConfig, ILogger<MenuViewComponent> logger) : ViewComponent
{
    public IViewComponentResult Invoke()
    {
        try
        {
            var settings = blogConfig.CustomMenuSettings;
            return View(settings);
        }
        catch (Exception e)
        {
            logger.LogError(e, e.Message);
            return Content("ERROR");
        }
    }
}

src/Moonglade.Web/Pages/Shared/_Aside.cshtml
@inject IConfiguration Configuration

<aside class="blog-sidebar col d-none d-lg-block">
    @if (BlogConfig.GeneralSettings.WidgetsProfile)
    {
        <partial name="_WidgetsProfile" />
    }

    @if (!string.IsNullOrWhiteSpace(BlogConfig.GeneralSettings.SideBarCustomizedHtmlPitch))
    {
        @Html.Raw(BlogConfig.GeneralSettings.SideBarCustomizedHtmlPitch)
    }

    @if (BlogConfig.GeneralSettings.WidgetsTags)
    {
        <section id="aside-tags" class="mt-4 mb-4">
            <div class="aside-widget p-3 rounded-3 shadow-sm border">
                <h6 class="card-subtitle mb-3 text-secondary">@SharedLocalizer["Tags"]</h6>
                <div>
                    <cache expires-after="@TimeSpan.FromMinutes(int.Parse(Configuration["Widget:TagsCacheMinutes"]!))">
                        <partial name="_WidgetRender" model="@("Tags")" />
                    </cache>
                    <hr />
                    <a asp-page="/Tags" class="card-link">
                        <i class="bi-tag me-1"></i>
                        @SharedLocalizer["All Tags"]
                    </a>
                </div>
            </div>
        </section>
    }

    @if (BlogConfig.GeneralSettings.WidgetsCategoryList)
    {
        <section id="aside-cats" class="mb-4">
            <div class="aside-widget p-3 rounded-3 shadow-sm border">
                <h6 class="card-subtitle mb-3 text-secondary">@SharedLocalizer["Categories"]</h6>
                @await Component.InvokeAsync("CategoryList", new { isMenu = false })
            </div>
        </section>
    }

    @if (BlogConfig.SocialLinkSettings.IsEnabled)
    {
        <section id="aside-sociallink" class="mb-4">
            <partial name="_WidgetRender" model="@("SocialLink")" />
        </section>
    }

    @if (BlogConfig.GeneralSettings.WidgetsFriendLink)
    {
        <section id="aside-friendlink" class="mb-4">
            <cache expires-after="@TimeSpan.FromMinutes(int.Parse(Configuration["Widget:FriendLinkCacheMinutes"]!))">
                <partial name="_WidgetRender" model="@("FriendLink")" />
            </cache>
        </section>
    }

    @if (BlogConfig.GeneralSettings.WidgetsSubscriptionButtons)
    {
        <section id="aside-subscription" class="text-center mb-4">
            <a class="btn btn-sm rounded-pill btn-outline-secondary me-2" href="#" data-bs-toggle="modal" data-bs-target="#subscriptionmodal">
                <i class="bi-rss"></i>
                RSS / Atom
            </a>

            @if (BlogConfig.AdvancedSettings.EnableOpml)
            {
                <a asp-controller="Subscription" asp-action="Opml" class="btn btn-sm rounded-pill btn-outline-secondary" target="_blank">
                    <i class="bi-code-slash"></i>
                    OPML
                </a>
            }
        </section>
    }
</aside>

@if (BlogConfig.GeneralSettings.WidgetsSubscriptionButtons)
{
    <partial name="_SubscriptionModal" />
}

src/Moonglade.Web/Pages/Shared/_AsideAdmin.cshtml
@{
    var currentPage = ViewContext.RouteData.Values["Page"]?.ToString();
}

<aside class="admin-nav">
    <section class="admin-nav-section mt-3 mb-3">
        <div class="list-group list-group-flush me-1">
            <a asp-page="/Admin/Post"
               class="list-group-item list-group-item-action @(currentPage is "/Admin/Post" or "/Admin/EditPost" or "/Admin/Draft" or "/Admin/RecycleBin" ? "active" : null)" title="Manage posts link">
                <div class="positioning-region">
                    <div class="content-region">
                        <i class="bi-file-earmark-richtext admin-nav-icon"></i>
                        @SharedLocalizer["Posts"]
                    </div>
                </div>
            </a>
            <a asp-page="/Admin/BlogPage"
               class="list-group-item list-group-item-action @(currentPage is "/Admin/BlogPage" or "/Admin/EditPage" ? "active" : null)" title="Manage pages link">
                <div class="positioning-region">
                    <div class="content-region">
                        <i class="bi-file-earmark-post admin-nav-icon"></i>
                        @SharedLocalizer["Pages"]
                    </div>
                </div>
            </a>
            <a asp-page="/Admin/Category"
               class="list-group-item list-group-item-action @(currentPage is "/Admin/Category" ? "active" : null)">
                <div class="positioning-region">
                    <div class="content-region">
                        <i class="bi-folder2 admin-nav-icon" title="Manage categories link"></i>
                        @SharedLocalizer["Categories"]
                    </div>
                </div>
            </a>
            @if (BlogConfig.CommentSettings.CommentProvider == CommentProvider.BuiltIn)
            {
                <a asp-page="/Admin/Comments"
                   class="list-group-item list-group-item-action @(currentPage is "/Admin/Comments" ? "active" : null)">
                    <div class="positioning-region">
                        <div class="content-region">
                            <i class="bi-chat-left-text admin-nav-icon" title="Manage comments link"></i>
                            @SharedLocalizer["Comments"]
                        </div>
                    </div>
                </a>
            }
            <a asp-page="/Admin/Tags"
               class="list-group-item list-group-item-action @(currentPage is "/Admin/Tags" ? "active" : null)">
                <div class="positioning-region">
                    <div class="content-region">
                        <i class="bi-tag admin-nav-icon" title="Manage tags link"></i>
                        @SharedLocalizer["Tags"]
                    </div>
                </div>
            </a>
            <a asp-page="/Admin/Menu"
               class="list-group-item list-group-item-action @(currentPage is "/Admin/Menu" ? "active" : null)">
                <div class="positioning-region">
                    <div class="content-region">
                        <i class="bi-menu-button-wide admin-nav-icon" title="Manage menus link"></i>
                        @SharedLocalizer["Menus"]
                    </div>
                </div>
            </a>
            <a asp-page="/Admin/FriendLink"
               class="list-group-item list-group-item-action @(currentPage is "/Admin/FriendLink" ? "active" : null)">
                <div class="positioning-region">
                    <div class="content-region">
                        <i class="bi-link-45deg admin-nav-icon" title="Manage friend links"></i>
                        @SharedLocalizer["Friend links"]
                    </div>
                </div>
            </a>
            <a asp-page="/Admin/Mention"
               class="list-group-item list-group-item-action @(currentPage is "/Admin/Mention" ? "active" : null)">
                <div class="positioning-region">
                    <div class="content-region">
                        <i class="bi-arrow-left-right admin-nav-icon" title="Manage mention link"></i>
                        @SharedLocalizer["Mentions"]
                    </div>
                </div>
            </a>
        </div>
    </section>
</aside>

src/Moonglade.Web/Pages/Shared/_Favicons.cshtml
<link rel="apple-touch-icon" sizes="180x180" href="~/apple-icon-180x180.png">
<link rel="icon" type="image/png" sizes="192x192" href="~/android-icon-192x192.png">
<link rel="icon" type="image/png" sizes="32x32" href="~/favicon-32x32.png">
<link rel="icon" type="image/png" sizes="96x96" href="~/favicon-96x96.png">
<link rel="icon" type="image/png" sizes="16x16" href="~/favicon-16x16.png">
<link rel="manifest" href="~/manifest.webmanifest">
<meta name="theme-color" content="#333333">

src/Moonglade.Web/Pages/Shared/_Footer.cshtml
@using Microsoft.AspNetCore.Builder
@using Moonglade.Utils

@inject IOptions<RequestLocalizationOptions> LocOptions
@{
    var cultureItems = LocOptions.Value.SupportedUICultures
        .Select(c => new { Value = c.Name, c.NativeName });
    var returnUrl = string.IsNullOrEmpty(Context.Request.Path) ? "~/" : $"~{Context.Request.Path.Value}";
}

<footer id="blog-footer" class="moonglade-footer pt-4 pb-4 d-print-none">
    <div class="container">
        <div class="row">
            <section id="footer-copyright" class="col-auto">
                <div>
                    @Html.Raw(Helper.FormatCopyright2Html(BlogConfig.GeneralSettings.Copyright))
                </div>
                <small>
                    Powered by <a href="https://github.com/EdiWang/Moonglade" target="_blank">Moonglade</a> @Helper.AppVersion
                </small>
            </section>

            @Html.Raw(BlogConfig.GeneralSettings.FooterCustomizedHtmlPitch)

            <section id="footer-language" class="col d-none d-sm-block text-end">
                <div class="language-selection d-print-none btn-group dropup">
                    <button type="button" class="btn btn-sm dropdown-toggle" data-bs-toggle="dropdown" aria-expanded="false">
                        <i class="bi-translate"></i> @SharedLocalizer["Languages"]
                    </button>
                    <ul class="dropdown-menu">
                        @foreach (var item in cultureItems)
                        {
                            <li>
                                <a class="dropdown-item"
                                   asp-controller="Settings"
                                   asp-action="SetLanguage"
                                   asp-route-returnUrl="@returnUrl"
                                   asp-route-culture="@item.Value">
                                    @item.NativeName
                                </a>
                            </li>
                        }
                    </ul>
                </div>
            </section>

            <section id="footer-language-mobile" class="col d-block d-md-none text-end font-125rem">
                <a href="#" data-bs-toggle="modal" data-bs-target="#langselectormodal" aria-label="Choose display language"><i class="bi-translate"></i></a>
            </section>
        </div>
    </div>
</footer>

<div class="modal fade" id="langselectormodal" tabindex="-1" role="dialog" aria-labelledby="langselectorLabel" aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h6 class="modal-title" id="langselectorLabel">Languages</h6>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close">
                </button>
            </div>
            <div class="modal-body">
                <ul class="list-unstyled">
                    @foreach (var item in cultureItems)
                    {
                        <li>
                            <a asp-controller="Settings" asp-action="SetLanguage" asp-route-returnUrl="@returnUrl" asp-route-culture="@item.Value" rel="nofollow">@item.NativeName</a>
                        </li>
                    }
                </ul>
            </div>
        </div>
    </div>
</div>

src/Moonglade.Web/Pages/Shared/_GoogleAnalytics.cshtml
@model string
<!-- Google tag (gtag.js) -->
<script async src="https://www.googletagmanager.com/gtag/js?id=@Model"></script>
<script>
    window.dataLayer = window.dataLayer || [];
    function gtag(){dataLayer.push(arguments);}
    gtag('js', new Date());

    gtag('config', '@Model');
</script>

src/Moonglade.Web/Pages/Shared/_Layout.cshtml
@using Moonglade.Utils
@using Microsoft.AspNetCore.Localization
@using System.Globalization
@inject IConfiguration Configuration
@inject IOptions<AnalyticsSettings> AnalyticsSettings

@{
    if (string.IsNullOrEmpty(BlogConfig.GeneralSettings.AvatarUrl))
    {
        BlogConfig.GeneralSettings.AvatarUrl = Url.Action("Avatar", "Assets");
    }

    // Resolve culture
    // Post language > User set display language > System default language
    var langCode = BlogConfig.GeneralSettings.DefaultLanguageCode;
    if (ViewBag.PostLangCode != null)
    {
        langCode = ViewBag.PostLangCode;
    }
    else
    {
        // CultureInfo.CurrentUICulture always has value, can not determine if is user selection
        var cultureCookie = Context.Request.Cookies[CookieRequestCultureProvider.DefaultCookieName];
        if (cultureCookie != null)
        {
            langCode = CultureInfo.CurrentUICulture.ToString().ToLower();
        }
    }

    bool useServerSideDarkMode = Helper.UseServerSideDarkMode(Configuration, Context);
}
<!DOCTYPE html>
<html lang="@langCode" data-bs-theme="@(useServerSideDarkMode ? "dark" : null)">
<head profile=@(BlogConfig.GeneralSettings.UseDublinCoreMetaData ? "http://dublincore.org/documents/dcq-html/" : null)>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    @if (BlogConfig.GeneralSettings.UseDublinCoreMetaData)
    {
        <link rel="schema.DC" href="http://purl.org/dc/elements/1.1/" />
        <link rel="schema.DCTERMS" href="http://purl.org/dc/terms/" />
    }

    <meta name="keywords" content="@(ViewBag.Keywords ?? Html.Raw(BlogConfig.GeneralSettings.MetaKeyword))" />

    @await RenderSectionAsync("meta", false)
    @if (IsSectionDefined("opengraph"))
    {
        @await RenderSectionAsync("opengraph", false)
    }
    else
    {
        <partial name="_OpenGraph" />
    }

    <metadesc description="@(ViewBag.MetaDescription ?? BlogConfig.GeneralSettings.Description)" />

    <title>
        @(ViewBag.TitlePrefix)@(null == ViewBag.TitlePrefix ? string.Empty : " - ")@BlogConfig.GeneralSettings.SiteTitle
    </title>

    @if (BlogConfig.ImageSettings.EnableCDNRedirect &&
    !string.IsNullOrWhiteSpace(BlogConfig.ImageSettings.CDNEndpoint))
    {
        <link rel="dns-prefetch" href="@Helper.GetDNSPrefetchUrl(BlogConfig.ImageSettings.CDNEndpoint)" />
    }

    @if (!string.IsNullOrWhiteSpace(BlogConfig.GeneralSettings.CanonicalPrefix))
    {
        <link rel="canonical" href="@(Helper.ResolveCanonicalUrl(BlogConfig.GeneralSettings.CanonicalPrefix, Context.Request.Path))" />
    }

    <link rel="start" title="@BlogConfig.GeneralSettings.SiteTitle" href="~/" />
    <rss title="@BlogConfig.GeneralSettings.SiteTitle" href="@Url.Action("Rss", "Subscription")" />
    @if (BlogConfig.AdvancedSettings.EnableOpenSearch)
    {
        <opensearch href="/opensearch" title="@BlogConfig.GeneralSettings.SiteTitle" />
    }

    @if (BlogConfig.AdvancedSettings.EnableFoaf)
    {
        <foaf href="/foaf.xml" />
    }
    <partial name="_Favicons" />
    <link href="~/lib/twitter-bootstrap/css/bootstrap.min.css" rel="stylesheet" asp-append-version="true" />
    <link href="~/lib/bootstrap-icons/bootstrap-icons.min.css" rel="stylesheet" asp-append-version="true" />
    <link href="~/fonts/font.css" rel="stylesheet" />
    <link href="~/css/base.css" rel="stylesheet" asp-append-version="true" />
    <link href="~/css/rwd.css" rel="stylesheet" asp-append-version="true" />
    @await RenderSectionAsync("head", false)
    <link href="~/theme.css" rel="stylesheet" asp-append-version="true" />
    @if (BlogConfig.AppearanceSettings.EnableCustomCss)
    {
        <link href="~/custom.css" rel="stylesheet" />
    }
    <environment exclude="Production">
        @inject IWebHostEnvironment WebHostEnvironment
        <script>
            console.warn('Moonglade is running in @(WebHostEnvironment.EnvironmentName) environment');
        </script>
    </environment>

    @if (AnalyticsSettings.Value.GoogleAnalytics.Enabled)
    {
        <partial name="_GoogleAnalytics" model="AnalyticsSettings.Value.GoogleAnalytics.GTagId" />
    }
</head>
<body class="@ViewBag.BodyClass">
    @if (BlogConfig.ContentSettings.ShowCalloutSection)
    {
        <section class="call-out">
            @Html.Raw(BlogConfig.ContentSettings.CalloutSectionHtmlPitch)
        </section>
    }

    <header class="sticky-top d-print-none">
        <nav id="blog-nav" class="navbar navbar-expand-lg navbar-moonglade" data-bs-theme="dark">
            <div class="container-xl">
                <div class="animbrand">
                    <h1 role="heading" class="moonglade-logo-heading">
                        <a class="moonglade-logo font-sairas navbar-brand animate" href="/">
                            @BlogConfig.GeneralSettings.LogoText
                        </a>
                    </h1>
                </div>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#blog-navbar-content" aria-controls="blog-navbar-content" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="collapse navbar-collapse" id="blog-navbar-content">
                    <ul class="navbar-nav me-auto">
                        <!-- System Nav Menu -->
                        <li id="navbar-dropdown-post" class="nav-item dropdown">
                            <a href="#" class="nav-link dropdown-toggle" role="button" data-bs-toggle="dropdown">
                                <i class="bi-folder2 nav-item-icon d-lg-none d-xl-inline-block"></i>
                                <strong>@SharedLocalizer["Categories"]</strong>
                            </a>
                            @await Component.InvokeAsync("CategoryList", new { isMenu = true })
                        </li>

                        <li class="nav-item">
                            <a asp-page="/Tags" class="nav-link">
                                <i class="bi-tag nav-item-icon d-lg-none d-xl-inline-block"></i>
                                <strong>@SharedLocalizer["Tags"]</strong>
                            </a>
                        </li>

                        <li class="nav-item">
                            <a asp-page="/Archive" class="nav-link">
                                <i class="bi-calendar3 nav-item-icon d-lg-none d-xl-inline-block"></i>
                                <strong>@SharedLocalizer["Archive"]</strong>
                            </a>
                        </li>

                        @await Component.InvokeAsync("Menu")
                    </ul>
                    <form class="d-flex search-form my-2 my-lg-0" action="/search" method="get">
                        <input id="term"
                               class="form-control bg-transparent me-sm-2"
                               type="search"
                               value=""
                               title="@SharedLocalizer["Search"]"
                               aria-label="Search"
                               placeholder="@SharedLocalizer["Search"]"
                               name="term"
                               maxlength="30">
                        <button class="btn btn-outline-light btn-search my-sm-0" type="submit" title="Search"><i class="bi-search"></i></button>
                    </form>
                </div>
            </div>
        </nav>
    </header>

    <div id="page-content" class="content">
        @if (null != ViewBag.HideSideBar && ViewBag.HideSideBar)
        {
            <main>
                @RenderBody()
            </main>
        }
        else
        {
            <section class="profile-mobile d-block d-sm-none d-print-none">
                <div class="card-background-container">
                    @if (BlogConfig.GeneralSettings.UseGravatarAsProfilePicture)
                    {
                        <gravatar class="card-bkimg" email="@BlogConfig.GeneralSettings.OwnerEmail" size="256" />
                    }
                    else
                    {
                        <img class="card-bkimg" alt="" aria-hidden="true" src="@BlogConfig.GeneralSettings.AvatarUrl" />
                    }
                </div>
                <div class="blogger-intro-content">
                    <div class="row">
                        <div class="col-3">
                            @if (BlogConfig.GeneralSettings.UseGravatarAsProfilePicture)
                            {
                                <gravatar class="rounded-circle blogger-head-pic"
                                          size="256"
                                          alt="@BlogConfig.GeneralSettings.OwnerName"
                                          email="@BlogConfig.GeneralSettings.OwnerEmail" />
                            }
                            else
                            {
                                <img src="@BlogConfig.GeneralSettings.AvatarUrl"
                                     alt="@BlogConfig.GeneralSettings.OwnerName"
                                     class="rounded-circle blogger-head-pic" />
                            }
                        </div>
                        <div class="col-9 position-relative">
                            <h4 class="text-center w-100 position-absolute top-50 start-50 translate-middle">
                                @BlogConfig.GeneralSettings.Description
                            </h4>
                        </div>
                    </div>
                </div>
            </section>
            <div class="container-xl mt-4 mb-5">
                <div class="row">
                    @if (BlogConfig.GeneralSettings.SideBarOption == SideBarOption.Left)
                    {
                        <partial name="_Aside" />
                    }

                    <main class="@(BlogConfig.GeneralSettings.SideBarOption == SideBarOption.Disabled ? null : "col")">
                        @RenderBody()
                    </main>

                    @if (BlogConfig.GeneralSettings.SideBarOption == SideBarOption.Right)
                    {
                        <partial name="_Aside" />
                    }
                </div>
            </div>
        }
    </div>
    <div class="clearfix"></div>
    <partial name="_Footer" />
    <partial name="_LightSwitch" />
    <partial name="_Toast" />

    <script src="~/lib/twitter-bootstrap/js/bootstrap.bundle.min.js" asp-append-version="true"></script>
    <script type="module" src="~/js/app/base.mjs" asp-append-version="true"></script>

    @await RenderSectionAsync("scripts", false)

    @if (AnalyticsSettings.Value.MicrosoftClarity.Enabled)
    {
        <partial name="_MicrosoftClarity" model="AnalyticsSettings.Value.MicrosoftClarity.ProjectId" />
    }

    @if (!string.IsNullOrWhiteSpace(BlogConfig.AdvancedSettings.FootScripts))
    {
        @Html.Raw(BlogConfig.AdvancedSettings.FootScripts)
    }
</body>
</html>

src/Moonglade.Web/Pages/Shared/_LayoutAdmin.cshtml
@inject IOptions<AuthenticationSettings> AuthOptions
@inject IConfiguration Configuration

@{
    if (string.IsNullOrEmpty(BlogConfig.GeneralSettings.AvatarUrl))
    {
        BlogConfig.GeneralSettings.AvatarUrl = Url.Action("Avatar", "Assets");
    }

    bool useServerSideDarkMode = Helper.UseServerSideDarkMode(Configuration, Context);
}
<!DOCTYPE html>
<html lang="@BlogConfig.GeneralSettings.DefaultLanguageCode" data-bs-theme="@(useServerSideDarkMode ? "dark" : null)">

<head>
    <title>
        @BlogConfig.GeneralSettings.SiteTitle @SharedLocalizer["Admin"] @(ViewBag.Title != null ? $"- {ViewBag.Title}" : null)
    </title>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1, user-scalable=no" />
    @await RenderSectionAsync("meta", false)
    <link rel="start" title="@BlogConfig.GeneralSettings.SiteTitle" href="~/" />
    <partial name="_Favicons" />
    <link href="~/lib/twitter-bootstrap/css/bootstrap.min.css" rel="stylesheet" asp-append-version="true" />
    <link href="~/lib/bootstrap-icons/bootstrap-icons.min.css" rel="stylesheet" asp-append-version="true" />
    <link href="~/css/base.css" rel="stylesheet" asp-append-version="true" />
    <link href="~/css/rwd.css" rel="stylesheet" asp-append-version="true" />
    <link href="~/css/admin.css" rel="stylesheet" asp-append-version="true" />
    <link href="~/theme.css" rel="stylesheet" />
    @await RenderSectionAsync("head", false)
</head>

<body class="admin-body bg-gray-1">
    <nav class="admin-navbar navbar sticky-top navbar-expand-lg navbar-moonglade" data-bs-theme="dark">
        <a class="navbar-brand font-sairas" asp-page="/Admin/Post">
            @BlogConfig.GeneralSettings.SiteTitle
        </a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent"
                aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>

        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav ms-auto">

                <li class="nav-item">
                    <a class="nav-link" asp-page="/Settings/General" title="settings link">
                        <i class="bi-gear"></i>
                    </a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" asp-page="/Admin/About" title="about link">
                        <i class="bi-info-circle"></i>
                    </a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" asp-page="/Index" target="_blank" title="home page link">
                        <i class="bi-house"></i>
                    </a>
                </li>
            </ul>

            <span class="navbar-text me-2">
                @if (AuthOptions.Value.Provider == AuthenticationProvider.Local)
                {
                    <a asp-page="/Admin/LocalAccount">
                        <img src="@BlogConfig.GeneralSettings.AvatarUrl" alt="@BlogConfig.GeneralSettings.OwnerName"
                             class="rounded-circle admin-nav-head-pic me-1" />
                        <userinfo user="User" user-info-display="PreferName"></userinfo>
                    </a>
                }
                else
                {
                    <img src="@BlogConfig.GeneralSettings.AvatarUrl" alt="@BlogConfig.GeneralSettings.OwnerName"
                         class="rounded-circle admin-nav-head-pic me-1" />
                    <userinfo user="User"></userinfo>
                }
            </span>

            <a class="navbar-text d-inline-block" asp-controller="Auth" asp-action="SignOut" title="Sign Out">
                <i class="bi-box-arrow-right"></i>
            </a>
        </div>
    </nav>
    <div class="d-flex admin-body-wrapper">
        <partial name="_AsideAdmin" />
        <div class="admin-main mt-3 mb-3 me-3 ms-3">
            @await RenderSectionAsync("admintoolbar", false)

            <div class="admin-main-body">
                @RenderBody()
            </div>
        </div>
    </div>

    <partial name="_Toast" />

    <script src="~/lib/twitter-bootstrap/js/bootstrap.bundle.min.js" asp-append-version="true"></script>
    <script type="module" src="~/js/app/base.mjs" asp-append-version="true"></script>

    @await RenderSectionAsync("scripts", false)
</body>

</html>

src/Moonglade.Web/Pages/Shared/_LightSwitch.cshtml
<div class="lightswitch d-print-none btn-group dropup">
    <button type="button" class="btn btn-sm btn-outline-accent dropdown-toggle" data-bs-toggle="dropdown" aria-expanded="false">
        @SharedLocalizer["Theme"]
    </button>
    <ul class="dropdown-menu">
        <li><a class="dropdown-item" href="javascript:;" data-theme="auto"><i class="bi-circle-half"></i> @SharedLocalizer["Auto"]</a></li>
        <li><hr class="dropdown-divider"></li>
        <li><a class="dropdown-item" href="javascript:;" data-theme="light"><i class="bi-brightness-high"></i> @SharedLocalizer["Light"]</a></li>
        <li><a class="dropdown-item" href="javascript:;" data-theme="dark"><i class="bi-moon"></i> @SharedLocalizer["Dark"]</a></li>
    </ul>
</div>

src/Moonglade.Web/Pages/Shared/_MicrosoftClarity.cshtml
@model string

<script type="text/javascript">
    (function(c,l,a,r,i,t,y){
        c[a]=c[a]||function(){(c[a].q=c[a].q||[]).push(arguments)};
        t=l.createElement(r);t.async=1;t.src="https://www.clarity.ms/tag/"+i;
        y=l.getElementsByTagName(r)[0];y.parentNode.insertBefore(t,y);
    })(window, document, "clarity", "script", "@Model");
</script>

src/Moonglade.Web/Pages/Shared/_OpenGraph.cshtml
<meta property="og:site_name" content="@BlogConfig.GeneralSettings.SiteTitle">
<meta property="og:title" content="@(ViewBag.TitlePrefix)@(null == ViewBag.TitlePrefix ? string.Empty : " - ")@BlogConfig.GeneralSettings.SiteTitle">
<meta property="og:type" content="website" />
<meta property="og:description" content="@BlogConfig.GeneralSettings.Description" />