src/Moonglade.Web/Controllers/CommentController.cs
using Microsoft.AspNetCore.Mvc.ModelBinding;
using Moonglade.Comments.Moderator;
using Moonglade.Email.Client;
using Moonglade.Web.Attributes;
using System.ComponentModel.DataAnnotations;

namespace Moonglade.Web.Controllers;

[Authorize]
[ApiController]
[Route("api/[controller]")]
[CommentProviderGate]
public class CommentController(
        IMediator mediator,
        IModeratorService moderator,
        IBlogConfig blogConfig,
        ILogger<CommentController> logger) : ControllerBase
{
    [HttpPost("{postId:guid}")]
    [AllowAnonymous]
    [ServiceFilter(typeof(ValidateCaptcha))]
    [ProducesResponseType(StatusCodes.Status201Created)]
    [ProducesResponseType(StatusCodes.Status204NoContent)]
    [ProducesResponseType(StatusCodes.Status400BadRequest)]
    [ProducesResponseType(StatusCodes.Status403Forbidden)]
    [ProducesResponseType<ModelStateDictionary>(StatusCodes.Status409Conflict)]
    public async Task<IActionResult> Create([NotEmpty] Guid postId, CommentRequest request)
    {
        if (!string.IsNullOrWhiteSpace(request.Email) && !Helper.IsValidEmailAddress(request.Email))
        {
            ModelState.AddModelError(nameof(request.Email), "Invalid Email address.");
            return BadRequest(ModelState.CombineErrorMessages());
        }

        if (!blogConfig.CommentSettings.EnableComments) return Forbid();

        if (blogConfig.CommentSettings.EnableWordFilter)
        {
            switch (blogConfig.CommentSettings.WordFilterMode)
            {
                case WordFilterMode.Mask:
                    request.Username = await moderator.Mask(request.Username);
                    request.Content = await moderator.Mask(request.Content);
                    break;
                case WordFilterMode.Block:
                    if (await moderator.Detect(request.Username, request.Content))
                    {
                        await Task.CompletedTask;
                        ModelState.AddModelError(nameof(request.Content), "Your comment contains bad bad word.");
                        return Conflict(ModelState);
                    }
                    break;
            }
        }

        var ip = (bool)HttpContext.Items["DNT"]! ? "N/A" : Helper.GetClientIP(HttpContext);
        var item = await mediator.Send(new CreateCommentCommand(postId, request, ip));

        if (null == item)
        {
            ModelState.AddModelError(nameof(postId), "Comment is closed for this post.");
            return Conflict(ModelState);
        }

        if (blogConfig.NotificationSettings.SendEmailOnNewComment)
        {
            try
            {
                await mediator.Publish(new CommentNotification(
                    item.Username,
                    item.Email,
                    item.IpAddress,
                    item.PostTitle,
                    item.CommentContent));
            }
            catch (Exception e)
            {
                logger.LogError(e, e.Message);
            }
        }

        if (blogConfig.CommentSettings.RequireCommentReview)
        {
            return Created("moonglade://empty", item);
        }

        return NoContent();
    }

    [HttpPut("{commentId:guid}/approval/toggle")]
    [ProducesResponseType<Guid>(StatusCodes.Status200OK)]
    public async Task<IActionResult> Approval([NotEmpty] Guid commentId)
    {
        await mediator.Send(new ToggleApprovalCommand([commentId]));
        return Ok(commentId);
    }

    [HttpDelete]
    [ProducesResponseType<Guid[]>(StatusCodes.Status200OK)]
    [ProducesResponseType<string>(StatusCodes.Status400BadRequest)]
    public async Task<IActionResult> Delete([FromBody][MinLength(1)] Guid[] commentIds)
    {
        await mediator.Send(new DeleteCommentsCommand(commentIds));
        return Ok(commentIds);
    }

    [HttpPost("{commentId:guid}/reply")]
    [ProducesResponseType<CommentReply>(StatusCodes.Status200OK)]
    [ProducesResponseType(StatusCodes.Status403Forbidden)]
    public async Task<IActionResult> Reply(
        [NotEmpty] Guid commentId,
        [Required][FromBody] string replyContent)
    {
        if (!blogConfig.CommentSettings.EnableComments) return Forbid();

        var reply = await mediator.Send(new ReplyCommentCommand(commentId, replyContent));
        if (blogConfig.NotificationSettings.SendEmailOnCommentReply && !string.IsNullOrWhiteSpace(reply.Email))
        {
            var postLink = GetPostUrl(reply.RouteLink);

            try
            {
                await mediator.Publish(new CommentReplyNotification(
                    reply.Email,
                    reply.CommentContent,
                    reply.Title,
                    reply.ReplyContentHtml,
                    postLink));
            }
            catch (Exception e)
            {
                logger.LogError(e, e.Message);
            }
        }

        return Ok(reply);
    }

    private string GetPostUrl(string routeLink)
    {
        var baseUri = new Uri(Helper.ResolveRootUrl(HttpContext, null, removeTailSlash: true));
        var link = new Uri(baseUri, $"post/{routeLink.ToLower()}");
        return link.ToString();
    }
}

src/Moonglade.Web/Controllers/PostController.cs
using Moonglade.Core.PostFeature;
using Moonglade.Data.Entities;
using Moonglade.IndexNow.Client;
using Moonglade.Pingback;
using Moonglade.Web.Attributes;
using Moonglade.Webmention;
using System.ComponentModel.DataAnnotations;

namespace Moonglade.Web.Controllers;

[Authorize]
[ApiController]
[Route("api/[controller]")]
public class PostController(
        IConfiguration configuration,
        IMediator mediator,
        IBlogConfig blogConfig,
        ITimeZoneResolver timeZoneResolver,
        ILogger<PostController> logger,
        CannonService cannonService) : ControllerBase
{
    [HttpPost("createoredit")]
    [ReadonlyMode]
    [TypeFilter(typeof(ClearBlogCache), Arguments =
    [
        BlogCacheType.SiteMap |
        BlogCacheType.Subscription
    ])]
    [ProducesResponseType(StatusCodes.Status200OK)]
    [ProducesResponseType(StatusCodes.Status409Conflict)]
    public async Task<IActionResult> CreateOrEdit(PostEditModel model)
    {
        try
        {
            if (!ModelState.IsValid) return Conflict(ModelState.CombineErrorMessages());

            var tzDate = timeZoneResolver.NowInTimeZone;
            if (model.ChangePublishDate &&
                model.PublishDate.HasValue &&
                model.PublishDate <= tzDate &&
                model.PublishDate.GetValueOrDefault().Year >= 1975)
            {
                model.PublishDate = timeZoneResolver.ToUtc(model.PublishDate.Value);
            }

            var postEntity = model.PostId == Guid.Empty ?
                await mediator.Send(new CreatePostCommand(model)) :
                await mediator.Send(new UpdatePostCommand(model.PostId, model));

            if (!model.IsPublished) return Ok(new { PostId = postEntity.Id });

            logger.LogInformation($"Trying to Ping URL for post: {postEntity.Id}");

            var baseUri = new Uri(Helper.ResolveRootUrl(HttpContext, null, removeTailSlash: true));
            var link = new Uri(baseUri, $"post/{postEntity.RouteLink.ToLower()}");

            NotifyExternalServices(postEntity.PostContent, link);
            ProcessIndexing(model.LastModifiedUtc, postEntity.LastModifiedUtc == postEntity.PubDateUtc, link);

            return Ok(new { PostId = postEntity.Id });
        }
        catch (Exception ex)
        {
            logger.LogError(ex, "Error Creating New Post.");
            return Conflict(ex.Message);
        }
    }

    private void NotifyExternalServices(string postContent, Uri link)
    {
        if (blogConfig.AdvancedSettings.EnablePingback)
        {
            cannonService.FireAsync<IPingbackSender>(async sender => await sender.TrySendPingAsync(link.ToString(), postContent));
        }

        if (blogConfig.AdvancedSettings.EnableWebmention)
        {
            cannonService.FireAsync<IWebmentionSender>(async sender => await sender.SendWebmentionAsync(link.ToString(), postContent));
        }
    }

    private void ProcessIndexing(string lastModifiedUtc, bool isNewPublish, Uri link)
    {
        bool indexCoolDown = true;
        var minimalIntervalMinutes = int.Parse(configuration["IndexNow:MinimalIntervalMinutes"]!);
        if (!string.IsNullOrWhiteSpace(lastModifiedUtc))
        {
            var lastSavedInterval = DateTime.Parse(lastModifiedUtc) - DateTime.UtcNow;
            indexCoolDown = lastSavedInterval.TotalMinutes > minimalIntervalMinutes;
        }

        if (isNewPublish || indexCoolDown)
        {
            cannonService.FireAsync<IIndexNowClient>(async sender => await sender.SendRequestAsync(link));
        }
    }

    [TypeFilter(typeof(ClearBlogCache), Arguments =
    [
        BlogCacheType.SiteMap |
        BlogCacheType.Subscription
    ])]
    [HttpPost("{postId:guid}/restore")]
    [ReadonlyMode]
    [ProducesResponseType(StatusCodes.Status204NoContent)]
    public async Task<IActionResult> Restore([NotEmpty] Guid postId)
    {
        await mediator.Send(new RestorePostCommand(postId));
        return NoContent();
    }

    [TypeFilter(typeof(ClearBlogCache), Arguments =
    [
        BlogCacheType.SiteMap |
        BlogCacheType.Subscription
    ])]
    [HttpDelete("{postId:guid}/recycle")]
    [ReadonlyMode]
    [ProducesResponseType(StatusCodes.Status204NoContent)]
    public async Task<IActionResult> Delete([NotEmpty] Guid postId)
    {
        await mediator.Send(new DeletePostCommand(postId, true));
        return NoContent();
    }

    [TypeFilter(typeof(ClearBlogCache), Arguments = [BlogCacheType.Subscription | BlogCacheType.SiteMap])]
    [HttpDelete("{postId:guid}/destroy")]
    [ReadonlyMode]
    [ProducesResponseType(StatusCodes.Status204NoContent)]
    public async Task<IActionResult> DeleteFromRecycleBin([NotEmpty] Guid postId)
    {
        await mediator.Send(new DeletePostCommand(postId));
        return NoContent();
    }

    [TypeFilter(typeof(ClearBlogCache), Arguments = [BlogCacheType.Subscription | BlogCacheType.SiteMap])]
    [HttpDelete("recyclebin")]
    [ReadonlyMode]
    [ProducesResponseType(StatusCodes.Status204NoContent)]
    public async Task<IActionResult> EmptyRecycleBin()
    {
        await mediator.Send(new EmptyRecycleBinCommand());
        return NoContent();
    }

    [TypeFilter(typeof(ClearBlogCache), Arguments = [BlogCacheType.Subscription | BlogCacheType.SiteMap])]
    [HttpPut("{postId:guid}/unpublish")]
    [ReadonlyMode]
    [ProducesResponseType(StatusCodes.Status204NoContent)]
    public async Task<IActionResult> Unpublish([NotEmpty] Guid postId)
    {
        await mediator.Send(new UnpublishPostCommand(postId));
        return NoContent();
    }

    [IgnoreAntiforgeryToken]
    [HttpPost("keep-alive")]
    [ProducesResponseType(StatusCodes.Status200OK)]
    public IActionResult KeepAlive([MaxLength(16)] string nonce)
    {
        return Ok(new
        {
            ServerTime = DateTime.UtcNow,
            Nonce = nonce
        });
    }
}

src/Moonglade.Web/Controllers/TagsController.cs
using Moonglade.Core.TagFeature;
using Moonglade.Data.Entities;
using System.ComponentModel.DataAnnotations;

namespace Moonglade.Web.Controllers;

[Authorize]
[ApiController]
[Route("api/[controller]")]
public class TagsController(IMediator mediator) : ControllerBase
{
    [HttpGet("names")]
    [ProducesResponseType<List<string>>(StatusCodes.Status200OK)]
    public async Task<IActionResult> Names()
    {
        var names = await mediator.Send(new GetTagNamesQuery());
        return Ok(names);
    }

    [HttpGet("list")]
    [ProducesResponseType<List<TagEntity>>(StatusCodes.Status200OK)]
    public async Task<IActionResult> List()
    {
        var list = await mediator.Send(new GetTagsQuery());
        return Ok(list);
    }

    [HttpPost]
    [ReadonlyMode]
    [ProducesResponseType(StatusCodes.Status200OK)]
    [ProducesResponseType(StatusCodes.Status400BadRequest)]
    [ProducesResponseType(StatusCodes.Status409Conflict)]
    public async Task<IActionResult> Create([Required][FromBody] string name)
    {
        if (!Helper.IsValidTagName(name)) return Conflict();

        await mediator.Send(new CreateTagCommand(name.Trim()));
        return Ok();
    }

    [HttpPut("{id:int}")]
    [ReadonlyMode]
    [ApiConventionMethod(typeof(DefaultApiConventions), nameof(DefaultApiConventions.Put))]
    public async Task<IActionResult> Update([Range(1, int.MaxValue)] int id, [Required][FromBody] string name)
    {
        var oc = await mediator.Send(new UpdateTagCommand(id, name));
        if (oc == OperationCode.ObjectNotFound) return NotFound();

        return NoContent();
    }

    [HttpDelete("{id:int}")]
    [ReadonlyMode]
    [ApiConventionMethod(typeof(DefaultApiConventions), nameof(DefaultApiConventions.Delete))]
    public async Task<IActionResult> Delete([Range(0, int.MaxValue)] int id)
    {
        var oc = await mediator.Send(new DeleteTagCommand(id));
        if (oc == OperationCode.ObjectNotFound) return NotFound();

        return NoContent();
    }
}

src/Moonglade.Web/Pages/Admin/Post.cshtml.cs
using Microsoft.AspNetCore.Mvc.RazorPages;
using Moonglade.Core.PostFeature;
using Moonglade.Data.Specifications;
using Moonglade.Web.PagedList;
using System.ComponentModel.DataAnnotations;

namespace Moonglade.Web.Pages.Admin;

public class PostModel(IMediator mediator) : PageModel
{
    private const int PageSize = 4;

    [BindProperty]
    [MaxLength(32)]
    public string SearchTerm { get; set; }

    public BasePagedList<PostSegment> PostSegments { get; set; }

    public async Task OnPost() => await GetPosts(1);

    public async Task OnGet(int pageIndex = 1, string searchTerm = null)
    {
        if (!string.IsNullOrWhiteSpace(searchTerm)) SearchTerm = searchTerm;

        await GetPosts(pageIndex);
    }

    private async Task GetPosts(int pageIndex)
    {
        var (posts, totalRows) = await mediator.Send(new ListPostSegmentQuery(PostStatus.Published, (pageIndex - 1) * PageSize, PageSize, SearchTerm));
        PostSegments = new(posts, pageIndex, PageSize, totalRows);
    }
}

src/Moonglade.Web/Pages/BlogPage.cshtml.cs
using Microsoft.AspNetCore.Mvc.RazorPages;
using Moonglade.Core.PageFeature;
using Moonglade.Data.Entities;

namespace Moonglade.Web.Pages;

public class BlogPageModel(IMediator mediator, ICacheAside cache, IConfiguration configuration) : PageModel
{
    public PageEntity BlogPage { get; set; }

    public async Task<IActionResult> OnGetAsync(string slug)
    {
        if (string.IsNullOrWhiteSpace(slug)) return BadRequest();

        var page = await cache.GetOrCreateAsync(BlogCachePartition.Page.ToString(), slug.ToLower(), async entry =>
        {
            entry.SlidingExpiration = TimeSpan.FromMinutes(int.Parse(configuration["Page:CacheMinutes"]!));

            var p = await mediator.Send(new GetPageBySlugQuery(slug));
            return p;
        });

        if (page is null || !page.IsPublished) return NotFound();

        BlogPage = page;

        if (page.UpdateTimeUtc.HasValue && bool.Parse(configuration["Page:LastModifiedHeader"]!))
        {
            Response.Headers.LastModified = page.UpdateTimeUtc.Value.ToString("R");

            if (Request.Headers.TryGetValue("If-Modified-Since", out var ifModifiedSince))
            {
                if (DateTime.TryParse(ifModifiedSince, out var ifModifiedSinceDate) &&
                    page.UpdateTimeUtc.Value <= ifModifiedSinceDate)
                {
                    return StatusCode(304);
                }
            }
        }

        return Page();
    }
}

src/Moonglade.Web/Pages/Error.cshtml.cs
using Microsoft.AspNetCore.Diagnostics;
using Microsoft.AspNetCore.Mvc.RazorPages;
using System.Diagnostics;

namespace Moonglade.Web.Pages;

[ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
[IgnoreAntiforgeryToken]
public class ErrorModel(ILogger<ErrorModel> logger) : PageModel
{
    public string RequestId { get; set; }

    public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);

    public void OnGet()
    {
        var requestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier;
        var exceptionFeature = HttpContext.Features.Get<IExceptionHandlerPathFeature>();
        if (exceptionFeature is not null)
        {
            // Get which route the exception occurred at
            var routeWhereExceptionOccurred = exceptionFeature.Path;

            // Get the exception that occurred
            var exceptionThatOccurred = exceptionFeature.Error;
            logger.LogError($"Error: {routeWhereExceptionOccurred}, " +
                             $"client IP: {Helper.GetClientIP(HttpContext)}, " +
                             $"request id: {requestId}", exceptionThatOccurred);
        }

        RequestId = requestId;
    }
}

src/Moonglade.Web/ViewComponents/CommentListViewComponent.cs
namespace Moonglade.Web.ViewComponents;

public class CommentListViewComponent(ILogger<CommentListViewComponent> logger, IMediator mediator) : ViewComponent
{
    public async Task<IViewComponentResult> InvokeAsync(Guid postId)
    {
        try
        {
            if (postId == Guid.Empty)
            {
                logger.LogError($"postId: {postId} is not a valid GUID");
                throw new ArgumentOutOfRangeException(nameof(postId));
            }

            var comments = await mediator.Send(new GetApprovedCommentsQuery(postId));
            return View(comments);
        }
        catch (Exception e)
        {
            logger.LogError(e, $"Error reading comments for post id: {postId}");
            return Content("ERROR");
        }
    }
}

src/Moonglade.Web/Pages/Post.cshtml
@page "/post/{year:int:min(1900):length(4)}/{month:int:range(1,12)}/{day:int:range(1,31)}/{slug:regex(^(?!-)([a-zA-Z0-9-]){{1,128}}$)}"
@model Moonglade.Web.Pages.PostModel
@using Moonglade.Utils

@Html.AntiForgeryToken()

@{
    ViewBag.BodyClass = "body-post-slug bg-gray-1";
    if (!Model.Post.IsFeedIncluded)
    {
        HttpContext.Response.Headers.Add("X-Robots-Tag", "noindex, nofollow");
    }

    ViewBag.PostLangCode = Model.Post.ContentLanguageCode;
    ViewBag.MetaDescription = Model.Post.ContentAbstract;

    @if (Model.Post.Tags.Any())
    {
        ViewBag.Keywords = string.Join(", ", Model.Post.Tags.Select(t => t.NormalizedName));
    }
}

@section meta {
    @if (!Model.Post.IsFeedIncluded)
    {
        <meta name="robots" content="noindex, nofollow" />
    }

    <meta name="title" content="@Model.Post.Title" />
    <meta name="displaydate" content="@Model.Post.PubDateUtc.GetValueOrDefault().ToString("u")">
    <meta name="copyright" content="(C) @DateTime.UtcNow.Year @BlogConfig.GeneralSettings.SiteTitle">
    <meta name="author" content="@(string.IsNullOrWhiteSpace(Model.Post.Author) ? BlogConfig.GeneralSettings.OwnerName : Model.Post.Author) " />
    <meta name="image-device-dpi" content="@BlogConfig.ImageSettings.FitImageToDevicePixelRatio.ToString().ToLower()" />
    <meta name="post-is-published" content="@Model.Post.IsPublished.ToString().ToLower()" />
    @if (BlogConfig.GeneralSettings.UseDublinCoreMetaData)
    {
        <partial name="_DublinCoreMetaData" model="Model" />
    }

    @if (BlogConfig.AdvancedSettings.EnableWebmention)
    {
        <link rel="webmention" href="@(Helper.ResolveCanonicalUrl(BlogConfig.GeneralSettings.CanonicalPrefix, "webmention"))">
    }
}

@section head {
    <link href="~/css/post.css" rel="stylesheet" asp-append-version="true" />
    <link href="~/css/highlighter-custom.css" rel="stylesheet" asp-append-version="true" />
    @if (BlogConfig.ContentSettings.DocumentOutline)
    {
        <link href="~/css/outline.css" rel="stylesheet" />
    }
}

@section opengraph {
    <meta property="og:site_name" content="@BlogConfig.GeneralSettings.SiteTitle">
    <meta property="og:title" content="@Model.Post.Title">
    <meta property="og:type" content="article" />
    <meta property="og:description" content="@Model.Post.ContentAbstract" />
    @if (!string.IsNullOrWhiteSpace(BlogConfig.GeneralSettings.CanonicalPrefix))
    {
        <meta property="og:url" content="@(Helper.ResolveCanonicalUrl(BlogConfig.GeneralSettings.CanonicalPrefix, HttpContext.Request.Path))" />
    }
}

@section scripts {
    <script src="~/js/3rd/highlight.min.js" asp-append-version="true"></script>
    <script src="~/js/3rd/katex.min.js"></script>

    @if (BlogConfig.ContentSettings.DocumentOutline)
    {
        <script src="~/js/app/documentoutline.js"></script>
        <script>
            let outline = new DocumentOutline(
                '.post-content h1, ' +
                '.post-content h2, ' +
                '.post-content h3, ' +
                '.post-content h4, ' +
                '.post-content h5');
        </script>
    }

    <script type="module" src="~/js/app/post.mjs" asp-append-version="true"></script>
    @if (BlogConfig.AdvancedSettings.WarnExternalLink)
    {
        <script type="module" src="~/js/app/externalLinkWarning.mjs" asp-append-version="true"></script>
    }
}

<article class="article-post-slug position-relative rounded-3 shadow-sm border bg-white mb-4" data-postid="@Model.Post.Id" lang="@Model.Post.ContentLanguageCode">
    @if (Model.Post.IsFeatured)
    {
        <partial name="_FeaturedTag" />
    }

    <header class="post-header mb-4 @(BlogConfig.ContentSettings.PostTitleAlignment == PostTitleAlignment.Center ? "text-center" : null)">
        <h1 class="post-title">
            @Model.Post.Title
        </h1>

        <div class="post-publish-info text-secondary mb-2">
            @if (!string.IsNullOrWhiteSpace(Model.Post.Author))
            {
                <i class="bi-person d-none d-sm-inline"></i>
                <span class="me-2 d-none d-sm-inline">@Model.Post.Author</span>
            }

            <i class="bi-calendar-event"></i>
            <span class="me-2">
                <time data-utc-label="@Model.Post.PubDateUtc.GetValueOrDefault().ToString("u")">
                    @DateOnly.FromDateTime(Model.Post.PubDateUtc.GetValueOrDefault()) (UTC)
                </time>
            </span>

            <i class="bi-clock"></i>
            <span id="reading-time"></span>

            @if (Model.IsViewCountEnabled)
            {
                <span id="view-count" class="ms-2"
                      title="@Model.PostView.RequestCount request(s), @(Model.PostView.ViewCount + 1) read(s) since @Model.PostView.BeginTimeUtc (UTC)">
                    <i class="bi-eye"></i>
                    <span>@(Model.PostView.ViewCount + 1)</span>
                </span>
            }
        </div>
    </header>

    @if (Model.Post.IsOutdated)
    {
        <partial name="_PostOutdatedMessage" />
    }

    @if (!string.IsNullOrWhiteSpace(Model.Post.HeroImageUrl))
    {
        <div class="post-hero-image-container text-center mb-3">
            <img src="@Helper.SterilizeLink(Model.Post.HeroImageUrl)" class="post-hero-image img-fluid rounded-3 shadow-sm" />
        </div>
    }

    <section class="post-content clearfix">
        <partial name="_PostContentRender" model="Model.Post.PostContent" />
    </section>

    @if (BlogConfig.ContentSettings.ShowPostFooter)
    {
        <section class="post-footer clearfix">
            @Html.Raw(BlogConfig.ContentSettings.PostFooterHtmlPitch)
        </section>
    }

    <partial name="_PostActions" model="Model.Post" />
</article>

@if (!Helper.GetAppDomainData<bool>("IsReadonlyMode") && BlogConfig.CommentSettings.EnableComments)
{
    var days = DateTime.UtcNow.Date.Subtract(Model.Post.PubDateUtc.GetValueOrDefault()).Days;

    if (BlogConfig.CommentSettings.CloseCommentAfterDays > 0 && days > BlogConfig.CommentSettings.CloseCommentAfterDays)
    {
        <div class="text-muted text-center">
            <span class="bi-dash-circle"></span>
            @SharedLocalizer["Comment is closed."]
        </div>
    }
    else
    {
        switch (BlogConfig.CommentSettings.CommentProvider)
        {
            case CommentProvider.BuiltIn:
                <div class="d-print-none">
                    @if (Model.Post.CommentEnabled)
                    {
                        <section class="comment-form-containter rounded-3 shadow-sm border bg-white mb-4">
                            <h5 class="card-subtitle mb-3 text-muted">
                                <i class="bi-chat-left-text"></i>
                                @SharedLocalizer["Comments"]
                            </h5>
                            <partial name="_CommentForm" />
                        </section>

                        <div id="thx-for-comment" class="alert alert-warning" style="display: none;">
                            @SharedLocalizer["Thanks, your comment is pending approval now."] <br />
                            @SharedLocalizer["It will show up once blog administrator approved your comment."]
                        </div>

                        <div id="thx-for-comment-non-review" class="alert alert-success" style="display: none;">
                            @SharedLocalizer["Thanks for your comment."] <br />
                            @SharedLocalizer["Refresh the page to see your comment."]
                        </div>

                        <section id="comments-list">
                            @await Component.InvokeAsync("CommentList", new { postId = Model.Post.Id })
                        </section>
                    }
                    else
                    {
                        <div class="text-muted text-center">
                            <span class="bi-ban"></span>
                            @SharedLocalizer["Comment of this post is disabled."]
                        </div>
                    }
                </div>
                break;
            case CommentProvider.ThirdParty:
                @Html.Raw(BlogConfig.CommentSettings.ThirdPartyCommentHtmlPitch)
                break;
        }
    }
}

<div class="modal fade" id="imgzoomModal" tabindex="-1" role="dialog" aria-labelledby="imgzoomModalLabel" aria-hidden="true">
    <div class="modal-dialog modal-imgzoom" role="document" style="max-width: 100%">
        <div class="modal-content">
            <img id="imgzoom" alt="imgzoom" class="img-fluid" />
        </div>
    </div>
</div>

@if (BlogConfig.AdvancedSettings.WarnExternalLink)
{
    <partial name="_ExternalLink" />
}

<partial name="_PostForestageAdmin" />

src/Moonglade.Web/Pages/_FeaturedTag.cshtml
<a asp-page="/Featured">
    <img src="~/images/featured-post.svg" class="featured-post-banner position-absolute" title="@SharedLocalizer["Featured"]" alt="@SharedLocalizer["Featured"]" />
</a>